"""Infrastructure execution hooks (§ req 8) — no business logic. Default implementation is no-op.

Lifecycle callbacks the Executor invokes: before_execute, after_execute, on_success, on_failure,
on_retry, on_cancel.
"""

from __future__ import annotations

from typing import Protocol

from app.models.queue import Task


class Hooks(Protocol):
    async def before_execute(self, task: Task) -> None: ...
    async def after_execute(self, task: Task) -> None: ...
    async def on_success(self, task: Task) -> None: ...
    async def on_failure(self, task: Task, error: BaseException) -> None: ...
    async def on_retry(self, task: Task, delay: float) -> None: ...
    async def on_cancel(self, task: Task) -> None: ...


class NoOpHooks:
    """No-op hooks used by default (structural implementation of the Hooks protocol)."""

    async def before_execute(self, task: Task) -> None: ...
    async def after_execute(self, task: Task) -> None: ...
    async def on_success(self, task: Task) -> None: ...
    async def on_failure(self, task: Task, error: BaseException) -> None: ...
    async def on_retry(self, task: Task, delay: float) -> None: ...
    async def on_cancel(self, task: Task) -> None: ...
