/**
 * Icon registry (D2 §10 — one outline family, lucide). Maps the string icon
 * names used in the route/status registries to their lucide components, so
 * data-driven surfaces (sidebar, palette) stay decoupled from imports.
 */
import {
  Activity,
  AudioWaveform,
  BadgeCheck,
  Bell,
  BookOpen,
  Brain,
  CalendarClock,
  CheckCircle,
  Circle,
  Clock,
  FileClock,
  FileText,
  FlaskConical,
  Flag,
  HeartPulse,
  Image as ImageIcon,
  LayoutDashboard,
  Library,
  LineChart,
  ListChecks,
  Loader,
  LogIn,
  type LucideIcon,
  MessageSquare,
  Moon,
  OctagonAlert,
  Pause,
  Pencil,
  Plug,
  Radio,
  ScrollText,
  Send,
  Settings,
  Shield,
  Sparkles,
  Sun,
  ToggleRight,
  User,
  UserPlus,
  Wallet,
} from 'lucide-react';

export const ICONS: Record<string, LucideIcon> = {
  // nav / routes
  sparkles: Sparkles,
  'log-in': LogIn,
  'user-plus': UserPlus,
  'layout-dashboard': LayoutDashboard,
  'message-square': MessageSquare,
  'book-open': BookOpen,
  brain: Brain,
  image: ImageIcon,
  library: Library,
  'flask-conical': FlaskConical,
  'chart-line': LineChart,
  radio: Radio,
  shield: Shield,
  plug: Plug,
  'heart-pulse': HeartPulse,
  'list-checks': ListChecks,
  'scroll-text': ScrollText,
  'file-clock': FileClock,
  'toggle-right': ToggleRight,
  wallet: Wallet,
  bell: Bell,
  settings: Settings,
  user: User,
  'file-text': FileText,
  // status vocabulary (D2 §11)
  loader: Loader,
  'audio-waveform': AudioWaveform,
  clock: Clock,
  activity: Activity,
  'check-circle': CheckCircle,
  'octagon-alert': OctagonAlert,
  flag: Flag,
  'badge-check': BadgeCheck,
  pencil: Pencil,
  send: Send,
  'calendar-clock': CalendarClock,
  pause: Pause,
  // theme
  sun: Sun,
  moon: Moon,
};

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? Circle;
}
